disabled_rules:
    - variable_name
    - function_parameter_count
    - colon
    - comma
    - line_length
    - force_cast
    - force_try
included:
    - Tourist
excluded:
    - Carthage
    - Pods
